parameters:
  - name: NoTests
    type: boolean
    default: false
    displayName: "Skip tests."

resources:
  repositories:
    - repository: templates
      type: github
      name: dlw-digitalworkplace/azure-devops-templates
      ref: refs/heads/main
      endpoint: GitHub

trigger:
  batch: true
  branches:
    include:
      - main
      - develop
  paths:
    include:
      - frontend/*

pool:
  vmImage: "ubuntu-latest"

variables:
  - template: pipelines/build/js/build.conventions.vars.yml@templates
    parameters:
      ProjectRoot: $(Build.SourcesDirectory)/frontend

  - template: pipelines/build/js/ci.branch.conventions.vars.yml@templates
    parameters:
      noTests: ${{ parameters.NoTests }}

steps:
  - checkout: self
    persistCredentials: true

  - template: pipelines/build/js/ci.yml@templates
    parameters:
      ProjectRoot: $(Build.SourcesDirectory)/frontend
      ExternalFeedCredentials: GitHub NPM packages
      NoTests: ${{ eq(variables.noTests, true) }}
      NodeVersion: 14.x
      WithPackageCache: true
      WithRelease: false
